create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id text primary key default gen_random_uuid()::text,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'user',
  plan text not null default 'free',
  avatar_color text not null default '#10b981',
  plan_expires_at timestamptz,
  referral_code text unique,
  referred_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  home_team text not null,
  away_team text not null,
  league text not null,
  league_icon text not null default '⚽',
  country text not null default 'International',
  kickoff_at timestamptz not null,
  tip text not null,
  market text not null default 'Match Result',
  odds double precision not null,
  confidence integer not null default 75,
  risk text not null default 'medium',
  analysis text,
  is_premium boolean not null default false,
  status text not null default 'upcoming',
  score_home integer,
  score_away integer,
  tipster text not null default 'Arena Tipster',
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id text primary key default gen_random_uuid()::text,
  user_id text not null references public.users(id) on delete cascade,
  reference text not null unique,
  email text,
  amount integer not null,
  currency text not null default 'KES',
  plan text not null,
  status text not null default 'initialized',
  provider text not null default 'paystack',
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.bet_slips (
  id text primary key default gen_random_uuid()::text,
  user_id text not null unique references public.users(id) on delete cascade,
  prediction_ids text not null default '[]',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id text primary key default gen_random_uuid()::text,
  user_id text not null references public.users(id) on delete cascade,
  type text not null,
  detail text,
  created_at timestamptz not null default now()
);

create table if not exists public.follows (
  id text primary key default gen_random_uuid()::text,
  follower_id text not null references public.users(id) on delete cascade,
  followee_id text not null,
  created_at timestamptz not null default now(),
  unique (follower_id, followee_id)
);

create table if not exists public.password_resets (
  id text primary key default gen_random_uuid()::text,
  user_id text not null references public.users(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists predictions_status_kickoff_idx
  on public.predictions(status, kickoff_at);
create index if not exists predictions_league_idx
  on public.predictions(league);
create index if not exists subscriptions_user_created_idx
  on public.subscriptions(user_id, created_at desc);
create index if not exists activity_logs_user_created_idx
  on public.activity_logs(user_id, created_at desc);
create index if not exists follows_followee_idx
  on public.follows(followee_id);
create index if not exists password_resets_user_idx
  on public.password_resets(user_id);

 drop trigger if exists bet_slips_set_updated_at on public.bet_slips;
create trigger bet_slips_set_updated_at
before update on public.bet_slips
for each row execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.predictions enable row level security;
alter table public.subscriptions enable row level security;
alter table public.bet_slips enable row level security;
alter table public.activity_logs enable row level security;
alter table public.follows enable row level security;
alter table public.password_resets enable row level security;

create policy "users can read their own profile"
  on public.users for select
  using (id = auth.uid()::text);
create policy "users can update their own profile"
  on public.users for update
  using (id = auth.uid()::text)
  with check (id = auth.uid()::text);

create policy "anyone can read predictions"
  on public.predictions for select
  using (true);
create policy "admins can create predictions"
  on public.predictions for insert
  with check (exists (
    select 1 from public.users
    where id = auth.uid()::text and role = 'admin'
  ));
create policy "admins can update predictions"
  on public.predictions for update
  using (exists (
    select 1 from public.users
    where id = auth.uid()::text and role = 'admin'
  ));
create policy "admins can delete predictions"
  on public.predictions for delete
  using (exists (
    select 1 from public.users
    where id = auth.uid()::text and role = 'admin'
  ));

create policy "users can read their subscriptions"
  on public.subscriptions for select
  using (user_id = auth.uid()::text);
create policy "users can create their subscriptions"
  on public.subscriptions for insert
  with check (user_id = auth.uid()::text);

create policy "users can manage their bet slip"
  on public.bet_slips for all
  using (user_id = auth.uid()::text)
  with check (user_id = auth.uid()::text);

create policy "users can read their activity"
  on public.activity_logs for select
  using (user_id = auth.uid()::text);
create policy "users can create their activity"
  on public.activity_logs for insert
  with check (user_id = auth.uid()::text);

create policy "users can manage their follows"
  on public.follows for all
  using (follower_id = auth.uid()::text)
  with check (follower_id = auth.uid()::text);

create policy "users cannot access password reset tokens"
  on public.password_resets for all
  using (false)
  with check (false);
