create extension if not exists pgcrypto;

create table if not exists users (
  id text primary key default gen_random_uuid()::text,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'user',
  plan text not null default 'free',
  avatar_color text not null default '#10b981',
  plan_expires_at timestamptz,
  referral_code text unique,
  referred_by text,
  created_at timestamptz not null default now()
);

create table if not exists predictions (
  id bigint generated by default as identity primary key,
  home_team text not null,
  away_team text not null,
  league text not null,
  league_icon text not null default '⚽',
  country text not null default 'International',
  kickoff_at timestamptz not null,
  tip text not null,
  market text not null default 'Match Result',
  odds double precision not null,
  confidence integer not null default 75,
  risk text not null default 'medium',
  analysis text,
  is_premium boolean not null default false,
  status text not null default 'upcoming',
  score_home integer,
  score_away integer,
  tipster text not null default 'Arena Tipster',
  created_at timestamptz not null default now()
);

create table if not exists subscriptions (
  id text primary key default gen_random_uuid()::text,
  user_id text not null references users(id) on delete cascade,
  reference text not null unique,
  email text,
  amount integer not null,
  currency text not null default 'KES',
  plan text not null,
  status text not null default 'initialized',
  provider text not null default 'paystack',
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists bet_slips (
  id text primary key default gen_random_uuid()::text,
  user_id text not null unique references users(id) on delete cascade,
  prediction_ids text not null default '[]',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists activity_logs (
  id text primary key default gen_random_uuid()::text,
  user_id text not null references users(id) on delete cascade,
  type text not null,
  detail text,
  created_at timestamptz not null default now()
);

create table if not exists follows (
  id text primary key default gen_random_uuid()::text,
  follower_id text not null references users(id) on delete cascade,
  followee_id text not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, followee_id)
);

create table if not exists password_resets (
  id text primary key default gen_random_uuid()::text,
  user_id text not null references users(id) on delete cascade,
  token text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists predictions_status_kickoff_idx on predictions(status, kickoff_at);
create index if not exists activity_logs_user_created_idx on activity_logs(user_id, created_at desc);
create index if not exists subscriptions_user_idx on subscriptions(user_id);

alter table users enable row level security;
alter table predictions enable row level security;
alter table subscriptions enable row level security;
alter table bet_slips enable row level security;
alter table activity_logs enable row level security;
alter table follows enable row level security;
alter table password_resets enable row level security;
